/* Author Name : Senith Kuruvitage
   Date        : June 24, 2026
   Program     : Design of a Hydroelectric Dam    */

#include<stdio.h>
int main()
{
	const float g = 9.80;               // g is the gravitational constant (9.80 m/s²).
	const float n = 0.9;                // η is the efficiency of the conversion (in this case, 90%).
	const float m = 1000;               // m is the mass of water flowing per second.
	float h, flowrate, work, power;     // h is the height of the dam.
	
	printf("Enter the height of the dam : \n");
	scanf("%f",&h);

	printf("Enter the flow rate of water : \n");
	scanf("%f",&flowrate);

	work = m*flowrate*g*h;
	power = (n*work)/1000000;

	printf("Predicted power generated by the hydroelectric dam : %.2f megawatts\n",power);

	return 0;

} // End of main function

